[package]
name = "stakpak-tui"
version = { workspace = true }
edition = "2024"

[dependencies]
stakpak-shared = { path = "../shared" }
ratatui = "0.26"
crossterm = "0.27"
tokio = { version = "1.39", features = ["full"] }
unicode-width = "0.2.0"
regex = "1.10"
serde_json = "1.0"