[subagents.ResearchAgent]
description = """
Fast research agent for code exploration, documentation lookup, and analysis. Ideal for understanding codebases, searching documentation, and gathering information without executing commands. Uses read-only tools for quick insights.
"""
max_steps = 20
allowed_tools = [
    "view",
    "local_code_search",
    "search_docs",
    "search_memory",
    "read_rulebook",
]

[subagents.SandboxResearchAgent]
description = """
Secure research agent that combines code analysis with safe command execution in an isolated container environment. 
Perfect for tasks requiring system inspection, file analysis, or running diagnostic commands while maintaining security.
Includes read-only access to cloud credentials (AWS, GCP, Azure, DigitalOcean) and your working directory.
Note: Slower than ResearchAgent due to containerization overhead, but provides additional command execution capabilities.
"""
max_steps = 30
allowed_tools = [
    "run_command",
    "view",
    "local_code_search",
    "search_docs",
    "search_memory",
    "read_rulebook",
]

[subagents.SandboxResearchAgent.warden]
enabled = true
volumes = [
    # stakpak config
    "~/.stakpak/config.toml:/home/agent/.stakpak/config.toml:ro",

    # working directory
    "./:/agent:ro",

    # cloud credentials
    "~/.aws:/home/agent/.aws:ro",
    "~/.config/gcloud:/home/agent/.config/gcloud:ro",
    "~/.digitalocean:/home/agent/.digitalocean:ro",
    "~/.azure:/home/agent/.azure:ro",
    "~/.kube:/home/agent/.kube:ro",
]
