[subagents.ResearchAgent]
description = "A general purpose research agent focused on research and analysis tasks"
max_steps = 10
allowed_tools = [
    "view",
    "local_code_search",
    "search_docs",
    "search_memory",
    "read_rulebook",
]
